# Spring profile
spring.profiles.active=local

# JPA / Hibernate (base config)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Logging
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.bike.store=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n
spring.jpa.hibernate.ddl-auto=create-drop  # or 'create' or 'update'






